CREATE DATABASE CloudToLocalLLM;
CREATE USER appuser WITH PASSWORD '1Cp:=4cxTF/9E!)$*k{0]@G?7Ku#6(j2';
GRANT ALL PRIVILEGES ON DATABASE CloudToLocalLLM TO appuser;
GRANT ALL ON SCHEMA public TO appuser;
