// Mocks generated by Mockito 5.4.6 from annotations
// in cloudtolocalllm/test/services/avatar_state_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:pistisai/database/drift_local_brain.dart' as _i3;
import 'package:pistisai/models/avatar/personality_models.dart' as _i6;
import 'package:pistisai/models/conversation.dart' as _i12;
import 'package:pistisai/models/main_chat_timeline_event.dart' as _i9;
import 'package:pistisai/models/message.dart' as _i13;
import 'package:pistisai/services/avatar/evolution_tracker.dart' as _i11;
import 'package:pistisai/services/avatar/markdown_sync_service.dart'
    as _i14;
import 'package:pistisai/services/avatar/personality_engine.dart'
    as _i10;
import 'package:pistisai/services/hermes_manager/main_chat_timeline_record.dart'
    as _i8;
import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$LocalBrainManager_1 extends _i1.SmartFake
    implements _i3.$LocalBrainManager {
  _Fake$LocalBrainManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$UsersTable_2 extends _i1.SmartFake implements _i3.$UsersTable {
  _Fake$UsersTable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ConversationsTable_3 extends _i1.SmartFake
    implements _i3.$ConversationsTable {
  _Fake$ConversationsTable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$MessagesTable_4 extends _i1.SmartFake
    implements _i3.$MessagesTable {
  _Fake$MessagesTable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$MainChatTimelineRecordsTable_5 extends _i1.SmartFake
    implements _i3.$MainChatTimelineRecordsTable {
  _Fake$MainChatTimelineRecordsTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AgentLogsTable_6 extends _i1.SmartFake
    implements _i3.$AgentLogsTable {
  _Fake$AgentLogsTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AgentsTable_7 extends _i1.SmartFake implements _i3.$AgentsTable {
  _Fake$AgentsTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AgentEventsTable_8 extends _i1.SmartFake
    implements _i3.$AgentEventsTable {
  _Fake$AgentEventsTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SyncQueueTable_9 extends _i1.SmartFake
    implements _i3.$SyncQueueTable {
  _Fake$SyncQueueTable_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$FileIndexTable_10 extends _i1.SmartFake
    implements _i3.$FileIndexTable {
  _Fake$FileIndexTable_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$FileContentCacheTable_11 extends _i1.SmartFake
    implements _i3.$FileContentCacheTable {
  _Fake$FileContentCacheTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$LlmProvidersTable_12 extends _i1.SmartFake
    implements _i3.$LlmProvidersTable {
  _Fake$LlmProvidersTable_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ModelCapacityTable_13 extends _i1.SmartFake
    implements _i3.$ModelCapacityTable {
  _Fake$ModelCapacityTable_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$LlmRequestsTable_14 extends _i1.SmartFake
    implements _i3.$LlmRequestsTable {
  _Fake$LlmRequestsTable_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AvatarProfilesTable_15 extends _i1.SmartFake
    implements _i3.$AvatarProfilesTable {
  _Fake$AvatarProfilesTable_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AchievementsTable_16 extends _i1.SmartFake
    implements _i3.$AchievementsTable {
  _Fake$AchievementsTable_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AvatarMemoryEntriesTable_17 extends _i1.SmartFake
    implements _i3.$AvatarMemoryEntriesTable {
  _Fake$AvatarMemoryEntriesTable_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ClipboardHistoryTable_18 extends _i1.SmartFake
    implements _i3.$ClipboardHistoryTable {
  _Fake$ClipboardHistoryTable_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ActionHistoryEntriesTable_19 extends _i1.SmartFake
    implements _i3.$ActionHistoryEntriesTable {
  _Fake$ActionHistoryEntriesTable_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$MacrosTable_20 extends _i1.SmartFake implements _i3.$MacrosTable {
  _Fake$MacrosTable_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AvatarPersonalityProfilesTable_21 extends _i1.SmartFake
    implements _i3.$AvatarPersonalityProfilesTable {
  _Fake$AvatarPersonalityProfilesTable_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$EvolutionHistoryTableTable_22 extends _i1.SmartFake
    implements _i3.$EvolutionHistoryTableTable {
  _Fake$EvolutionHistoryTableTable_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ConversationDepthMetricsTable_23 extends _i1.SmartFake
    implements _i3.$ConversationDepthMetricsTable {
  _Fake$ConversationDepthMetricsTable_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ConversationMemoriesTable_24 extends _i1.SmartFake
    implements _i3.$ConversationMemoriesTable {
  _Fake$ConversationMemoriesTable_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AgentThoughtsTable_25 extends _i1.SmartFake
    implements _i3.$AgentThoughtsTable {
  _Fake$AgentThoughtsTable_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ConscienceDecisionsTable_26 extends _i1.SmartFake
    implements _i3.$ConscienceDecisionsTable {
  _Fake$ConscienceDecisionsTable_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_27 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_28 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_29 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_30 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_31 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_32 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_33 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAvatarPersonalityProfile_34 extends _i1.SmartFake
    implements _i3.AvatarPersonalityProfile {
  _FakeAvatarPersonalityProfile_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_35 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_36<T> extends _i1.SmartFake implements _i5.Future<T> {
  _FakeFuture_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_37<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_38<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_39<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_40<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_40(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_41<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_41(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_42<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_42(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_43<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_43(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_44 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_44(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExtendedAvatarProfile_45 extends _i1.SmartFake
    implements _i6.ExtendedAvatarProfile {
  _FakeExtendedAvatarProfile_45(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvolutionDecision_46 extends _i1.SmartFake
    implements _i6.EvolutionDecision {
  _FakeEvolutionDecision_46(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalBrain].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalBrain extends _i1.Mock implements _i3.LocalBrain {
  MockLocalBrain() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i2.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_0(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i2.MigrationStrategy);

  @override
  _i3.$LocalBrainManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$LocalBrainManager_1(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i3.$LocalBrainManager);

  @override
  _i3.$UsersTable get users => (super.noSuchMethod(
        Invocation.getter(#users),
        returnValue: _Fake$UsersTable_2(
          this,
          Invocation.getter(#users),
        ),
      ) as _i3.$UsersTable);

  @override
  _i3.$ConversationsTable get conversations => (super.noSuchMethod(
        Invocation.getter(#conversations),
        returnValue: _Fake$ConversationsTable_3(
          this,
          Invocation.getter(#conversations),
        ),
      ) as _i3.$ConversationsTable);

  @override
  _i3.$MessagesTable get messages => (super.noSuchMethod(
        Invocation.getter(#messages),
        returnValue: _Fake$MessagesTable_4(
          this,
          Invocation.getter(#messages),
        ),
      ) as _i3.$MessagesTable);

  @override
  _i3.$MainChatTimelineRecordsTable get mainChatTimelineRecords =>
      (super.noSuchMethod(
        Invocation.getter(#mainChatTimelineRecords),
        returnValue: _Fake$MainChatTimelineRecordsTable_5(
          this,
          Invocation.getter(#mainChatTimelineRecords),
        ),
      ) as _i3.$MainChatTimelineRecordsTable);

  @override
  _i3.$AgentLogsTable get agentLogs => (super.noSuchMethod(
        Invocation.getter(#agentLogs),
        returnValue: _Fake$AgentLogsTable_6(
          this,
          Invocation.getter(#agentLogs),
        ),
      ) as _i3.$AgentLogsTable);

  @override
  _i3.$AgentsTable get agents => (super.noSuchMethod(
        Invocation.getter(#agents),
        returnValue: _Fake$AgentsTable_7(
          this,
          Invocation.getter(#agents),
        ),
      ) as _i3.$AgentsTable);

  @override
  _i3.$AgentEventsTable get agentEvents => (super.noSuchMethod(
        Invocation.getter(#agentEvents),
        returnValue: _Fake$AgentEventsTable_8(
          this,
          Invocation.getter(#agentEvents),
        ),
      ) as _i3.$AgentEventsTable);

  @override
  _i3.$SyncQueueTable get syncQueue => (super.noSuchMethod(
        Invocation.getter(#syncQueue),
        returnValue: _Fake$SyncQueueTable_9(
          this,
          Invocation.getter(#syncQueue),
        ),
      ) as _i3.$SyncQueueTable);

  @override
  _i3.$FileIndexTable get fileIndex => (super.noSuchMethod(
        Invocation.getter(#fileIndex),
        returnValue: _Fake$FileIndexTable_10(
          this,
          Invocation.getter(#fileIndex),
        ),
      ) as _i3.$FileIndexTable);

  @override
  _i3.$FileContentCacheTable get fileContentCache => (super.noSuchMethod(
        Invocation.getter(#fileContentCache),
        returnValue: _Fake$FileContentCacheTable_11(
          this,
          Invocation.getter(#fileContentCache),
        ),
      ) as _i3.$FileContentCacheTable);

  @override
  _i3.$LlmProvidersTable get llmProviders => (super.noSuchMethod(
        Invocation.getter(#llmProviders),
        returnValue: _Fake$LlmProvidersTable_12(
          this,
          Invocation.getter(#llmProviders),
        ),
      ) as _i3.$LlmProvidersTable);

  @override
  _i3.$ModelCapacityTable get modelCapacity => (super.noSuchMethod(
        Invocation.getter(#modelCapacity),
        returnValue: _Fake$ModelCapacityTable_13(
          this,
          Invocation.getter(#modelCapacity),
        ),
      ) as _i3.$ModelCapacityTable);

  @override
  _i3.$LlmRequestsTable get llmRequests => (super.noSuchMethod(
        Invocation.getter(#llmRequests),
        returnValue: _Fake$LlmRequestsTable_14(
          this,
          Invocation.getter(#llmRequests),
        ),
      ) as _i3.$LlmRequestsTable);

  @override
  _i3.$AvatarProfilesTable get avatarProfiles => (super.noSuchMethod(
        Invocation.getter(#avatarProfiles),
        returnValue: _Fake$AvatarProfilesTable_15(
          this,
          Invocation.getter(#avatarProfiles),
        ),
      ) as _i3.$AvatarProfilesTable);

  @override
  _i3.$AchievementsTable get achievements => (super.noSuchMethod(
        Invocation.getter(#achievements),
        returnValue: _Fake$AchievementsTable_16(
          this,
          Invocation.getter(#achievements),
        ),
      ) as _i3.$AchievementsTable);

  @override
  _i3.$AvatarMemoryEntriesTable get avatarMemoryEntries => (super.noSuchMethod(
        Invocation.getter(#avatarMemoryEntries),
        returnValue: _Fake$AvatarMemoryEntriesTable_17(
          this,
          Invocation.getter(#avatarMemoryEntries),
        ),
      ) as _i3.$AvatarMemoryEntriesTable);

  @override
  _i3.$ClipboardHistoryTable get clipboardHistory => (super.noSuchMethod(
        Invocation.getter(#clipboardHistory),
        returnValue: _Fake$ClipboardHistoryTable_18(
          this,
          Invocation.getter(#clipboardHistory),
        ),
      ) as _i3.$ClipboardHistoryTable);

  @override
  _i3.$ActionHistoryEntriesTable get actionHistoryEntries =>
      (super.noSuchMethod(
        Invocation.getter(#actionHistoryEntries),
        returnValue: _Fake$ActionHistoryEntriesTable_19(
          this,
          Invocation.getter(#actionHistoryEntries),
        ),
      ) as _i3.$ActionHistoryEntriesTable);

  @override
  _i3.$MacrosTable get macros => (super.noSuchMethod(
        Invocation.getter(#macros),
        returnValue: _Fake$MacrosTable_20(
          this,
          Invocation.getter(#macros),
        ),
      ) as _i3.$MacrosTable);

  @override
  _i3.$AvatarPersonalityProfilesTable get avatarPersonalityProfiles =>
      (super.noSuchMethod(
        Invocation.getter(#avatarPersonalityProfiles),
        returnValue: _Fake$AvatarPersonalityProfilesTable_21(
          this,
          Invocation.getter(#avatarPersonalityProfiles),
        ),
      ) as _i3.$AvatarPersonalityProfilesTable);

  @override
  _i3.$EvolutionHistoryTableTable get evolutionHistoryTable =>
      (super.noSuchMethod(
        Invocation.getter(#evolutionHistoryTable),
        returnValue: _Fake$EvolutionHistoryTableTable_22(
          this,
          Invocation.getter(#evolutionHistoryTable),
        ),
      ) as _i3.$EvolutionHistoryTableTable);

  @override
  _i3.$ConversationDepthMetricsTable get conversationDepthMetrics =>
      (super.noSuchMethod(
        Invocation.getter(#conversationDepthMetrics),
        returnValue: _Fake$ConversationDepthMetricsTable_23(
          this,
          Invocation.getter(#conversationDepthMetrics),
        ),
      ) as _i3.$ConversationDepthMetricsTable);

  @override
  _i3.$ConversationMemoriesTable get conversationMemories =>
      (super.noSuchMethod(
        Invocation.getter(#conversationMemories),
        returnValue: _Fake$ConversationMemoriesTable_24(
          this,
          Invocation.getter(#conversationMemories),
        ),
      ) as _i3.$ConversationMemoriesTable);

  @override
  _i3.$AgentThoughtsTable get agentThoughts => (super.noSuchMethod(
        Invocation.getter(#agentThoughts),
        returnValue: _Fake$AgentThoughtsTable_25(
          this,
          Invocation.getter(#agentThoughts),
        ),
      ) as _i3.$AgentThoughtsTable);

  @override
  _i3.$ConscienceDecisionsTable get conscienceDecisions => (super.noSuchMethod(
        Invocation.getter(#conscienceDecisions),
        returnValue: _Fake$ConscienceDecisionsTable_26(
          this,
          Invocation.getter(#conscienceDecisions),
        ),
      ) as _i3.$ConscienceDecisionsTable);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
      ) as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i2.DatabaseSchemaEntity>[],
      ) as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_27(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_28(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.DriftDatabaseOptions);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_29(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i2.StreamQueryUpdateRules);

  @override
  _i2.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_30(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i7.dummyValue<_i2.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_31(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_32(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_33(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<List<_i8.MainChatTimelineRecord>> loadMainChatTimelineRecords(
          {String? conversationId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMainChatTimelineRecords,
          [],
          {#conversationId: conversationId},
        ),
        returnValue: _i5.Future<List<_i8.MainChatTimelineRecord>>.value(
            <_i8.MainChatTimelineRecord>[]),
      ) as _i5.Future<List<_i8.MainChatTimelineRecord>>);

  @override
  _i5.Future<List<_i9.MainChatTimelineEvent>> loadMainChatTimelineEvents(
          {String? conversationId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMainChatTimelineEvents,
          [],
          {#conversationId: conversationId},
        ),
        returnValue: _i5.Future<List<_i9.MainChatTimelineEvent>>.value(
            <_i9.MainChatTimelineEvent>[]),
      ) as _i5.Future<List<_i9.MainChatTimelineEvent>>);

  @override
  _i5.Future<void> appendMainChatTimelineEvents(
    Iterable<_i9.MainChatTimelineEvent>? events, {
    required String? sourceDeviceId,
    String? conversationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #appendMainChatTimelineEvents,
          [events],
          {
            #sourceDeviceId: sourceDeviceId,
            #conversationId: conversationId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearMainChatTimelineRecords() => (super.noSuchMethod(
        Invocation.method(
          #clearMainChatTimelineRecords,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ModelCapacityData?> getModelCapacity(String? modelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModelCapacity,
          [modelId],
        ),
        returnValue: _i5.Future<_i3.ModelCapacityData?>.value(),
      ) as _i5.Future<_i3.ModelCapacityData?>);

  @override
  _i5.Future<List<_i3.ModelCapacityData>> getAllModelCapacities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllModelCapacities,
          [],
        ),
        returnValue: _i5.Future<List<_i3.ModelCapacityData>>.value(
            <_i3.ModelCapacityData>[]),
      ) as _i5.Future<List<_i3.ModelCapacityData>>);

  @override
  _i5.Stream<List<_i3.ModelCapacityData>> watchAllModelCapacities() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllModelCapacities,
          [],
        ),
        returnValue: _i5.Stream<List<_i3.ModelCapacityData>>.empty(),
      ) as _i5.Stream<List<_i3.ModelCapacityData>>);

  @override
  _i5.Future<void> updateUsage(
    String? modelId,
    int? concurrentChange,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUsage,
          [
            modelId,
            concurrentChange,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> syncUsageFromHeader(
    String? modelId,
    int? remaining,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncUsageFromHeader,
          [
            modelId,
            remaining,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Conversation>> getConversations(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversations,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i3.Conversation>>.value(<_i3.Conversation>[]),
      ) as _i5.Future<List<_i3.Conversation>>);

  @override
  _i5.Future<List<_i3.Message>> getMessages(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [conversationId],
        ),
        returnValue: _i5.Future<List<_i3.Message>>.value(<_i3.Message>[]),
      ) as _i5.Future<List<_i3.Message>>);

  @override
  _i5.Future<int> addMessage(_i3.MessagesCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMessage,
          [entry],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> createConversation(_i3.ConversationsCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createConversation,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> upsertAgent(_i3.AgentsCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertAgent,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Agent>> getAllAgents() => (super.noSuchMethod(
        Invocation.method(
          #getAllAgents,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Agent>>.value(<_i3.Agent>[]),
      ) as _i5.Future<List<_i3.Agent>>);

  @override
  _i5.Future<_i3.Agent?> getAgentById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getAgentById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Agent?>.value(),
      ) as _i5.Future<_i3.Agent?>);

  @override
  _i5.Future<int> deleteOldAgents(Duration? age) => (super.noSuchMethod(
        Invocation.method(
          #deleteOldAgents,
          [age],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> addAgentEvent(_i3.AgentEventsCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAgentEvent,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AgentEvent>> getUnsyncedEvents({int? limit = 100}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedEvents,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.AgentEvent>>.value(<_i3.AgentEvent>[]),
      ) as _i5.Future<List<_i3.AgentEvent>>);

  @override
  _i5.Future<void> markEventsSynced(List<String>? eventIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #markEventsSynced,
          [eventIds],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AgentEvent>> getEventsByType(
    String? eventType, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByType,
          [eventType],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.AgentEvent>>.value(<_i3.AgentEvent>[]),
      ) as _i5.Future<List<_i3.AgentEvent>>);

  @override
  _i5.Future<int> deleteOldSyncedEvents(Duration? age) => (super.noSuchMethod(
        Invocation.method(
          #deleteOldSyncedEvents,
          [age],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> indexFile(_i3.FileIndexCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexFile,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> indexFilesBatch(List<_i3.FileIndexCompanion>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexFilesBatch,
          [entries],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.FileIndexData>> searchFilesByName(
    String? query, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFilesByName,
          [query],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.FileIndexData>>.value(<_i3.FileIndexData>[]),
      ) as _i5.Future<List<_i3.FileIndexData>>);

  @override
  _i5.Future<List<_i3.FileIndexData>> searchFilesByPath(
    String? query, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchFilesByPath,
          [query],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.FileIndexData>>.value(<_i3.FileIndexData>[]),
      ) as _i5.Future<List<_i3.FileIndexData>>);

  @override
  _i5.Future<List<_i3.FileIndexData>> getFilesByExtension(
    String? ext, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilesByExtension,
          [ext],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.FileIndexData>>.value(<_i3.FileIndexData>[]),
      ) as _i5.Future<List<_i3.FileIndexData>>);

  @override
  _i5.Future<int> getIndexedFileCount() => (super.noSuchMethod(
        Invocation.method(
          #getIndexedFileCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getIndexedDirectoryCount() => (super.noSuchMethod(
        Invocation.method(
          #getIndexedDirectoryCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> clearFileIndex() => (super.noSuchMethod(
        Invocation.method(
          #clearFileIndex,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i3.FileIndexData?> getFileByPath(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileByPath,
          [path],
        ),
        returnValue: _i5.Future<_i3.FileIndexData?>.value(),
      ) as _i5.Future<_i3.FileIndexData?>);

  @override
  _i5.Future<int> deleteFileFromIndex(String? path) => (super.noSuchMethod(
        Invocation.method(
          #deleteFileFromIndex,
          [path],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> cacheFileContent(
    String? filePath,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheFileContent,
          [
            filePath,
            content,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.FileContentCacheData?> getCachedContent(String? filePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedContent,
          [filePath],
        ),
        returnValue: _i5.Future<_i3.FileContentCacheData?>.value(),
      ) as _i5.Future<_i3.FileContentCacheData?>);

  @override
  _i5.Future<int> clearOldCache(Duration? age) => (super.noSuchMethod(
        Invocation.method(
          #clearOldCache,
          [age],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> enqueueSync(_i3.SyncQueueCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueSync,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.SyncQueueData>> getPendingSyncItems({int? limit = 100}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSyncItems,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.SyncQueueData>>.value(<_i3.SyncQueueData>[]),
      ) as _i5.Future<List<_i3.SyncQueueData>>);

  @override
  _i5.Future<int> dequeueSync(int? id) => (super.noSuchMethod(
        Invocation.method(
          #dequeueSync,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> incrementRetry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #incrementRetry,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> clearOldSyncQueue(Duration? age) => (super.noSuchMethod(
        Invocation.method(
          #clearOldSyncQueue,
          [age],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> logAgent(
    String? level,
    String? message, {
    String? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAgent,
          [
            level,
            message,
          ],
          {#context: context},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AgentLog>> getRecentLogs({int? limit = 100}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentLogs,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.AgentLog>>.value(<_i3.AgentLog>[]),
      ) as _i5.Future<List<_i3.AgentLog>>);

  @override
  _i5.Future<List<_i3.AgentLog>> getLogsByLevel(
    String? level, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogsByLevel,
          [level],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.AgentLog>>.value(<_i3.AgentLog>[]),
      ) as _i5.Future<List<_i3.AgentLog>>);

  @override
  _i5.Future<int> clearOldLogs(Duration? age) => (super.noSuchMethod(
        Invocation.method(
          #clearOldLogs,
          [age],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.AvatarProfile>> getAllAvatarProfiles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAvatarProfiles,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.AvatarProfile>>.value(<_i3.AvatarProfile>[]),
      ) as _i5.Future<List<_i3.AvatarProfile>>);

  @override
  _i5.Future<_i3.AvatarProfile?> getActiveAvatarProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAvatarProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.AvatarProfile?>.value(),
      ) as _i5.Future<_i3.AvatarProfile?>);

  @override
  _i5.Future<void> updateAvatarProfile(_i3.AvatarProfilesCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAvatarProfile,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> awardXP(int? amount) => (super.noSuchMethod(
        Invocation.method(
          #awardXP,
          [amount],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Achievement>> getAllAchievements() => (super.noSuchMethod(
        Invocation.method(
          #getAllAchievements,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.Achievement>>.value(<_i3.Achievement>[]),
      ) as _i5.Future<List<_i3.Achievement>>);

  @override
  _i5.Future<List<_i3.Achievement>> getUnlockedAchievements() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnlockedAchievements,
          [],
        ),
        returnValue:
            _i5.Future<List<_i3.Achievement>>.value(<_i3.Achievement>[]),
      ) as _i5.Future<List<_i3.Achievement>>);

  @override
  _i5.Future<void> insertAchievement(_i3.AchievementsCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAchievement,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unlockAchievement(String? achievementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlockAchievement,
          [achievementId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> insertAvatarMemoryEntry(
          _i3.AvatarMemoryEntriesCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAvatarMemoryEntry,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AvatarMemoryEntry>> getAllAvatarMemoryEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAvatarMemoryEntries,
          [],
        ),
        returnValue: _i5.Future<List<_i3.AvatarMemoryEntry>>.value(
            <_i3.AvatarMemoryEntry>[]),
      ) as _i5.Future<List<_i3.AvatarMemoryEntry>>);

  @override
  _i5.Future<List<_i3.AvatarMemoryEntry>> searchMemoriesByTag(String? tag) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMemoriesByTag,
          [tag],
        ),
        returnValue: _i5.Future<List<_i3.AvatarMemoryEntry>>.value(
            <_i3.AvatarMemoryEntry>[]),
      ) as _i5.Future<List<_i3.AvatarMemoryEntry>>);

  @override
  _i5.Future<int> deleteOldAvatarMemories(DateTime? cutoff) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldAvatarMemories,
          [cutoff],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.ConversationMemory>> getMemoriesForConversation(
          String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemoriesForConversation,
          [conversationId],
        ),
        returnValue: _i5.Future<List<_i3.ConversationMemory>>.value(
            <_i3.ConversationMemory>[]),
      ) as _i5.Future<List<_i3.ConversationMemory>>);

  @override
  _i5.Future<void> insertMemory(_i3.ConversationMemoriesCompanion? memory) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMemory,
          [memory],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ConversationMemory>> searchMemoriesByContent(
          String? searchTerm) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMemoriesByContent,
          [searchTerm],
        ),
        returnValue: _i5.Future<List<_i3.ConversationMemory>>.value(
            <_i3.ConversationMemory>[]),
      ) as _i5.Future<List<_i3.ConversationMemory>>);

  @override
  _i5.Future<int> deleteMemoriesForConversation(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMemoriesForConversation,
          [conversationId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.ConversationMemory>> getRecentMemories(
          {int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentMemories,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.ConversationMemory>>.value(
            <_i3.ConversationMemory>[]),
      ) as _i5.Future<List<_i3.ConversationMemory>>);

  @override
  _i5.Future<void> insertClipboardEntry(_i3.ClipboardHistoryCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertClipboardEntry,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ClipboardHistoryData>> getAllClipboardEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClipboardEntries,
          [],
        ),
        returnValue: _i5.Future<List<_i3.ClipboardHistoryData>>.value(
            <_i3.ClipboardHistoryData>[]),
      ) as _i5.Future<List<_i3.ClipboardHistoryData>>);

  @override
  _i5.Future<int> deleteClipboardEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteClipboardEntry,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> clearClipboardHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearClipboardHistory,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> insertActionHistoryEntry(
          _i3.ActionHistoryEntriesCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertActionHistoryEntry,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ActionHistoryEntry>> getAllActionHistoryEntries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllActionHistoryEntries,
          [],
        ),
        returnValue: _i5.Future<List<_i3.ActionHistoryEntry>>.value(
            <_i3.ActionHistoryEntry>[]),
      ) as _i5.Future<List<_i3.ActionHistoryEntry>>);

  @override
  _i5.Future<int> clearActionHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearActionHistory,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> insertMacro(_i3.MacrosCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMacro,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Macro>> getAllMacros() => (super.noSuchMethod(
        Invocation.method(
          #getAllMacros,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Macro>>.value(<_i3.Macro>[]),
      ) as _i5.Future<List<_i3.Macro>>);

  @override
  _i5.Future<_i3.Macro?> getMacroById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMacroById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Macro?>.value(),
      ) as _i5.Future<_i3.Macro?>);

  @override
  _i5.Future<void> updateMacroLastUsed(String? id) => (super.noSuchMethod(
        Invocation.method(
          #updateMacroLastUsed,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> deleteMacro(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMacro,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<dynamic>> getAllProviders() => (super.noSuchMethod(
        Invocation.method(
          #getAllProviders,
          [],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<dynamic> getProviderById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProviderById,
          [id],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> getDefaultProvider() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultProvider,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<List<dynamic>> getProvidersByType(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProvidersByType,
          [type],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<void> upsertProvider(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertProvider,
          [data],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> deleteProvider(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProvider,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> setDefaultProvider(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultProvider,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasProviders() => (super.noSuchMethod(
        Invocation.method(
          #hasProviders,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.AvatarPersonalityProfile> getAvatarProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvatarProfile,
          [],
        ),
        returnValue: _i5.Future<_i3.AvatarPersonalityProfile>.value(
            _FakeAvatarPersonalityProfile_34(
          this,
          Invocation.method(
            #getAvatarProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i3.AvatarPersonalityProfile>);

  @override
  _i5.Future<void> updateAvatarTraits(Map<String, double>? traits) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAvatarTraits,
          [traits],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAgentName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #updateAgentName,
          [name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateEvolutionStage(String? stage) => (super.noSuchMethod(
        Invocation.method(
          #updateEvolutionStage,
          [stage],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> recordEvolution({
    required String? fromStage,
    required String? toStage,
    required String? triggerReason,
    required String? context,
    required String? confirmedBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordEvolution,
          [],
          {
            #fromStage: fromStage,
            #toStage: toStage,
            #triggerReason: triggerReason,
            #context: context,
            #confirmedBy: confirmedBy,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.EvolutionHistory>> getEvolutionHistory() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvolutionHistory,
          [],
        ),
        returnValue: _i5.Future<List<_i3.EvolutionHistory>>.value(
            <_i3.EvolutionHistory>[]),
      ) as _i5.Future<List<_i3.EvolutionHistory>>);

  @override
  _i5.Future<void> addConversationDepthMetrics(
          _i3.ConversationDepthMetricsCompanion? metric) =>
      (super.noSuchMethod(
        Invocation.method(
          #addConversationDepthMetrics,
          [metric],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ConversationDepthMetric>> getDepthMetrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDepthMetrics,
          [],
        ),
        returnValue: _i5.Future<List<_i3.ConversationDepthMetric>>.value(
            <_i3.ConversationDepthMetric>[]),
      ) as _i5.Future<List<_i3.ConversationDepthMetric>>);

  @override
  _i5.Future<List<_i3.ConversationDepthMetric>> getDepthMetricsForConversation(
          String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDepthMetricsForConversation,
          [conversationId],
        ),
        returnValue: _i5.Future<List<_i3.ConversationDepthMetric>>.value(
            <_i3.ConversationDepthMetric>[]),
      ) as _i5.Future<List<_i3.ConversationDepthMetric>>);

  @override
  _i5.Future<void> insertThought(_i3.AgentThoughtsCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertThought,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AgentThought>> getThoughtsByAgent(
    String? agent, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThoughtsByAgent,
          [agent],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.AgentThought>>.value(<_i3.AgentThought>[]),
      ) as _i5.Future<List<_i3.AgentThought>>);

  @override
  _i5.Future<List<_i3.AgentThought>> getThoughtsByChannel(
    String? channel, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThoughtsByChannel,
          [channel],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.AgentThought>>.value(<_i3.AgentThought>[]),
      ) as _i5.Future<List<_i3.AgentThought>>);

  @override
  _i5.Future<List<_i3.AgentThought>> getRecentThoughts({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentThoughts,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.AgentThought>>.value(<_i3.AgentThought>[]),
      ) as _i5.Future<List<_i3.AgentThought>>);

  @override
  _i5.Future<List<_i3.AgentThought>> getThoughtsByType(
    String? thoughtType, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThoughtsByType,
          [thoughtType],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.AgentThought>>.value(<_i3.AgentThought>[]),
      ) as _i5.Future<List<_i3.AgentThought>>);

  @override
  _i5.Future<void> insertDecision(_i3.ConscienceDecisionsCompanion? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDecision,
          [entry],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ConscienceDecision>> getPendingDecisions(
          {int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingDecisions,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.ConscienceDecision>>.value(
            <_i3.ConscienceDecision>[]),
      ) as _i5.Future<List<_i3.ConscienceDecision>>);

  @override
  _i5.Future<List<_i3.ConscienceDecision>> getDecisionsByStatus(
    String? status, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecisionsByStatus,
          [status],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.ConscienceDecision>>.value(
            <_i3.ConscienceDecision>[]),
      ) as _i5.Future<List<_i3.ConscienceDecision>>);

  @override
  _i5.Future<List<_i3.ConscienceDecision>> getDecisionsByRiskLevel(
    String? riskLevel, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecisionsByRiskLevel,
          [riskLevel],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.ConscienceDecision>>.value(
            <_i3.ConscienceDecision>[]),
      ) as _i5.Future<List<_i3.ConscienceDecision>>);

  @override
  _i5.Future<List<_i3.ConscienceDecision>> getAllDecisions({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDecisions,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i3.ConscienceDecision>>.value(
            <_i3.ConscienceDecision>[]),
      ) as _i5.Future<List<_i3.ConscienceDecision>>);

  @override
  _i5.Future<void> updateDecisionVerdict(
    String? id,
    String? verdict,
    String? reviewer,
    String? reasoning,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDecisionVerdict,
          [
            id,
            verdict,
            reviewer,
            reasoning,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ConscienceDecision?> getDecisionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDecisionById,
          [id],
        ),
        returnValue: _i5.Future<_i3.ConscienceDecision?>.value(),
      ) as _i5.Future<_i3.ConscienceDecision?>);

  @override
  _i2.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_35(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Ret> computeWithDatabase<Ret, DB extends _i2.GeneratedDatabase>({
    required _i5.FutureOr<Ret> Function(DB)? computation,
    required DB Function(_i2.DatabaseConnection)? connect,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #computeWithDatabase,
          [],
          {
            #computation: computation,
            #connect: connect,
          },
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<Ret>(
                this,
                Invocation.method(
                  #computeWithDatabase,
                  [],
                  {
                    #computation: computation,
                    #connect: connect,
                  },
                ),
              ),
              (Ret v) => _i5.Future<Ret>.value(v),
            ) ??
            _FakeFuture_36<Ret>(
              this,
              Invocation.method(
                #computeWithDatabase,
                [],
                {
                  #computation: computation,
                  #connect: connect,
                },
              ),
            ),
      ) as _i5.Future<Ret>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
          _i4.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i5.Stream<T>.empty(),
      ) as _i5.Stream<T>);

  @override
  T alias<T, D>(
    _i2.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates(
          [_i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
      ) as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
          _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_36<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
          _i2.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_37<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
          _i2.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_38<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_39<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_40<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
          Iterable<_i2.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_41<_i2.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
          _i2.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_42<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
      ) as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_43<_i2.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_43<_i2.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_36<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_36<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i7.ifNotNull(
              _i7.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_36<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_44(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_44(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [PersonalityEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonalityEngine extends _i1.Mock implements _i10.PersonalityEngine {
  MockPersonalityEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.ExtendedAvatarProfile> getPersonality() => (super.noSuchMethod(
        Invocation.method(
          #getPersonality,
          [],
        ),
        returnValue: _i5.Future<_i6.ExtendedAvatarProfile>.value(
            _FakeExtendedAvatarProfile_45(
          this,
          Invocation.method(
            #getPersonality,
            [],
          ),
        )),
      ) as _i5.Future<_i6.ExtendedAvatarProfile>);

  @override
  _i5.Future<void> updatePersonality(_i6.PersonalityTraits? traits) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePersonality,
          [traits],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAgentName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #updateAgentName,
          [name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.EvolutionDecision> validateEvolutionRequest(
    String? requestedStage,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateEvolutionRequest,
          [
            requestedStage,
            reason,
          ],
        ),
        returnValue:
            _i5.Future<_i6.EvolutionDecision>.value(_FakeEvolutionDecision_46(
          this,
          Invocation.method(
            #validateEvolutionRequest,
            [
              requestedStage,
              reason,
            ],
          ),
        )),
      ) as _i5.Future<_i6.EvolutionDecision>);
}

/// A class which mocks [EvolutionTracker].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvolutionTracker extends _i1.Mock implements _i11.EvolutionTracker {
  MockEvolutionTracker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> trackConversation(_i12.Conversation? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackConversation,
          [conversation],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<double> calculateComplexity(List<_i13.Message>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateComplexity,
          [messages],
        ),
        returnValue: _i5.Future<double>.value(0.0),
      ) as _i5.Future<double>);

  @override
  _i5.Future<double> calculateEmotionalDepth(List<_i13.Message>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateEmotionalDepth,
          [messages],
        ),
        returnValue: _i5.Future<double>.value(0.0),
      ) as _i5.Future<double>);

  @override
  _i5.Future<double> calculateNovelty(List<_i13.Message>? messages) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateNovelty,
          [messages],
        ),
        returnValue: _i5.Future<double>.value(0.0),
      ) as _i5.Future<double>);

  @override
  _i5.Future<bool> hasEvolutionPatterns() => (super.noSuchMethod(
        Invocation.method(
          #hasEvolutionPatterns,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [MarkdownSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarkdownSyncService extends _i1.Mock
    implements _i14.MarkdownSyncService {
  MockMarkdownSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> syncPersonality(_i6.ExtendedAvatarProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncPersonality,
          [profile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> syncMemory() => (super.noSuchMethod(
        Invocation.method(
          #syncMemory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> syncContext() => (super.noSuchMethod(
        Invocation.method(
          #syncContext,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> syncAll(_i6.ExtendedAvatarProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncAll,
          [profile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.ExtendedAvatarProfile?> loadPersonalityFromMarkdown() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPersonalityFromMarkdown,
          [],
        ),
        returnValue: _i5.Future<_i6.ExtendedAvatarProfile?>.value(),
      ) as _i5.Future<_i6.ExtendedAvatarProfile?>);

  @override
  _i5.Future<bool> hasMarkdownBackup() => (super.noSuchMethod(
        Invocation.method(
          #hasMarkdownBackup,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> clearMarkdownFiles() => (super.noSuchMethod(
        Invocation.method(
          #clearMarkdownFiles,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
