apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: streaming-proxy-backendconfig
  namespace: Pistisai
spec:
  timeoutSec: 3600
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 3001

